apiVersion: v1
kind: Service
metadata:
  name: xui-panel-service
  namespace: xui-vpn
spec:
  selector:
    app: xui-panel
  ports:
    - name: http
      protocol: TCP
      port: 2053
      targetPort: 2053
  type: ClusterIP
