      env:
        - name: XUI_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: xui-admin-secret
              key: XUI_ADMIN_USER
        - name: XUI_ADMIN_PASS
          valueFrom:
            secretKeyRef:
              name: xui-admin-secret
              key: XUI_ADMIN_PASS
