apiVersion: v1
kind: Service
metadata:
  name: xui
  namespace: xui-vpn
spec:
  clusterIP: None
  selector:
    app: xui-panel
  ports:
    - name: web
      port: 2053
      targetPort: 2053
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: xui-panel
  namespace: xui-vpn
spec:
  serviceName: xui
  replicas: 1
  selector:
    matchLabels:
      app: xui-panel
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app: xui-panel
    spec:
      hostNetwork: true
      automountServiceAccountToken: false
      containers:
        - name: xui
          image: ghcr.io/mhsanaei/3x-ui:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data
              mountPath: /etc/x-ui
          resources:
            limits:
              memory: 512Mi
              cpu: 1000m
            requests:
              memory: 256Mi
              cpu: 500m
          securityContext:
            privileged: false
            capabilities:
              add:
                - NET_ADMIN
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: xui-data-pvc
