      - name: Run dgoss tests
        run: |
          docker volume create x-ui-test-db
          export GOSS_FILES_PATH=./goss-tests
          export GOSS_SLEEP=10
          export GOSS_FILES_STRATEGY=cp
          dgoss run -v x-ui-test-db:/etc/x-ui -p 2053:2053 -p 2096:2096 ${{ env.IMAGE_NAME }}:test
